class MyException:
    def __init__(self):
        print('__init__ method of MyException class is called.')

